sudo: required
services:
    - docker

before_install:
    - docker build -f NishM/docker-react -t Dockerfile.dev .    

script:
    - docker run NishM/docker-react npm run test -- --coverage



     