sudo: required
language: generic
services:
    - docker

before_install:
    - docker build  -t  nishdevops/docker-react  -f  Dockerfile.dev .    

script:
    - docker run -e CI=true nishdevops/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk  
  region: #region from the AWS 
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "bucket-name"
  bucket_path: "docker"
   on:
    branch: master
   access_key_id: $AWS_SECRET_KEY
    secure: $AWS_ACCESS_KEY