sudo: required
services:
    - docker

before_install:
    - docker build  -t  nishdevops/docker-react  -f  Dockerfile.dev .    

script:
    - docker run nishdevops/docker-react npm run test -- --coverage  